apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "Harness Actions"
inputs:
  url:
    description: 'harness url'
    required: false
    default: 'https://app.harness.io/'
  token:
    description: 'harness api  token'
    required: true
  org-name:
    description: 'organization name'
    required: true
  project-name:
    description: 'project name'
    required: true
  pipeline-name:
    description: 'pipeline name'
    required: true


runs:
  using: composite
  steps:
    - id: invoke-harness-action
      name: invoke-harness-action
      uses: docker://registry.saas-dev.beescloud.com/testing/harness-actions:latest
      shell: sh
      env: 
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"HARNESSACTIONS","password":"${{ inputs.token }}","orgName":"${{ inputs.org-name }}","projectName":"${{ inputs.project-name }}","jobName":"${{ inputs.pipeline-name }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        echo '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"HARNESSACTIONS","password":"${{ inputs.token }}","orgName":"${{ inputs.org-name }}","projectName":"${{ inputs.project-name }}","jobName":"${{ inputs.pipeline-name }}"}}'

        cd /app
        ./harness_actions_app invoke -i $CONFIG_JSON
